"use strict";
const number1 = 23.6;
const number2 = 0x78CF;
const number3 = 0o577;
const number4 = 0b110001;
console.log(number1);
console.log(number2);
console.log(number3);
console.log(number4);
console.log(typeof number1);
console.log(typeof number2);
console.log(typeof number3);
console.log(typeof number4);
